---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(ggplot2)
library(car)



```

```{r load_data}
# Use this R-Chunk to import all your datasets!

```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
#View(airquality)

#?airquality

graph <- ggplot(airquality, aes(x=Temp))+ 
  geom_histogram(binwidth = 5, fill="skyblue", color="skyblue4")+
  labs(title="xyz",
  subtitle = "abc",
  x="Temperature",
  y="Frequency")
  
graph


#graph 2
test <- ggplot(airquality, aes(x=as.factor(Month), y=Temp))+
  geom_boxplot(fill="skyblue", 
               color="skyblue4")+
  labs(title="Maximiun",
  subtitle = "May to September",
  x="Temperature",
  y="Frequency")
test

abc <- ggplot(airquality, aes(x=Temp, y=Wind))+
  geom_point()+
  geom_smooth(method="lm", se=F, formula=y~x)
abc

air.lm <- lm(Wind ~ Temp, data=airquality)
summary(air.lm)

# QQ PLot 
plot_5 <- qqPlot(air.lm$residuals)
plot_5

#residuals vs. fitted-values plo
plot_6 <- plot(air.lm, which=1)
plot_6

# residuals vs. order
plot_7 <- plot(air.lm$residuals)
plot_7

```



```{r simulatingTheRegressionModel, eval=FALSE}
## Simulating Data from a Regression Model
## This R-chunk is meant to be played in your R Console.
## It allows you to explore how the various elements
## of the regression model combine together to "create"
## data and then use the data to "re-create" the line.

#set.seed(101) #Allows us to always get the same "random" sample
              #Change to a new number to get a new sample

  n <- 30 #set the sample size

  X_i <- runif(n, 15, 45) #Gives n random values from a uniform distribution between 15 to 45.

  beta0 <- 89 #Our choice for the y-intercept. 

  beta1 <- -1.25 #Our choice for the slope. 

  sigma <- 8 #Our choice for the std. deviation of the error terms.

  epsilon_i <- rnorm(n, 0, sigma) #Gives n random values from a normal distribution with mean = 0, st. dev. = sigma.

  Y_i <- beta0 + beta1*X_i + epsilon_i #Create Y using the normal error regression model

  fabData <- data.frame(y=Y_i, x=X_i) #Store the data as data

  View(fabData) 
  
  #In the real world, we begin with data (like fabData) and try to recover the model that (we assume) was used to created it.

  fab.lm <- lm(y ~ x, data=fabData) #Fit an estimated regression model to the fabData.

  summary(fab.lm) #Summarize your model. 

  plot(y ~ x, data=fabData) #Plot the data.

  abline(fab.lm) #Add the estimated regression line to your plot.

# Now for something you can't do in real life... but since we created the data...

  abline(beta0, beta1, lty=2) #Add the true regression line to your plot using a dashed line (lty=2). 

  legend("topleft", legend=c("True Line", "Estimated Line"), lty=c(2,1), bty="n") #Add a legend to your plot specifying which line is which.
  

```



```{r plot_data}


graph <- ggplot(mtcars, aes(x=mpg))+ 
  geom_histogram(binwidth = 5, fill="skyblue", color="skyblue4")+
  labs(title="xyz",
  subtitle = "abc",
  x="mpg",
  y="cars")
  
graph


mpg.lm <- lm(mpg ~ wt, data=mtcars)
summary(mpg.lm)

abc <- ggplot(mtcars, aes(x=wt, y=mpg))+
  geom_point()+
  geom_smooth(method="lm", se=F, formula=y~x)
abc


# QQ PLot 
plot_5 <- qqPlot(mpg.lm$residuals)
plot_5

#residuals vs. fitted-values plo
plot_6 <- plot(mpg.lm, which=1)
plot_6

# residuals vs. order
plot_7 <- plot(mpg.lm$residuals)
plot_7



```


## Conclusions
