---
title: "R Notebook"
output: html_notebook
---

```{r}
library(alr4)
```


```{r}
?BGSall

View(BGSall)
```



```{r}

lm.height <- lm(HT18 ~ HT2, data=BGSall)
summary(lm.height)

plot(HT18 ~ HT2, data=BGSall)
abline(lm.height)

```


$$
  \underbrace{Y_i}_\text{Height 18} = {\beta_0} + {\beta_1} \underbrace{X_i}_\text{Height 2} + \epsilon_i \quad \text{where} \ \epsilon_i \sim N(0, \sigma^2)
$$



```{r}
confint(lm.height, level = 0.95)
```


```{r}
lm.height <- lm(HT18 ~ HT2, data=BGSall)
par(mfrow=c(1,3))

#residuals vs. fitted-values plo
plot(lm.height, which=1:2)


# residuals vs. order
plot(lm.height$residuals,
     main="Residuals Vs. Order")


#sum(coef(weather.lm)*c(1, 70))

```





```{r}

#use the fitted model to predict the value for the new observation
pred <- predict(lm.height, data.frame(HT2=83.82), interval="prediction")
pred
```



```{r}
?wblake

View(wblake)
```




```{r}
lm.fish <- lm(Scale ~ Length, data=wblake)
summary(lm.fish)
plot(Scale ~ Length, data=wblake)
abline(lm.fish)

pred_original <- (predict(lm.fish, data.frame(Length=250), interval="prediction"))


```



```{r}
lm.fish <- lm(Scale ~ Length, data=wblake)
par(mfrow=c(1,3))

#residuals vs. fitted-values plo
plot(lm.fish, which=1:2)


# residuals vs. order
plot(lm.fish$residuals,
     main="Residuals Vs. Order")


#sum(coef(weather.lm)*c(1, 70))

```


```{r}
boxCox(lm.fish)
```



```{r}
y = sqrt(wblake$Scale)

lm_new <- lm(y ~ wblake$Length)
b <- coef(lm_new)

summary(lm_new)
fish <- lm(y ~ Length, data=wblake)

pred <- (predict(fish, data.frame(Length=250), interval="prediction"))^2

# 
# plot(Scale ~ Length, data=wblake)
# abline(lm.fish)


last_plot <- ggplot(wblake, aes(x=Length, y=y))+
  geom_point()+
  geom_smooth(method="lm", se=F, formula=y~x, fullrange=TRUE)
  # geom_hline(aes(y=6.053607,  linetype="Purcahse Price"), color="red")+
  # geom_hline(aes(yend=10.0595, linetype="Sale Price"), color="red")+
  #stat_function(fun = function(x) ((b[1] + b[2]*x)^2), color='black')



last_plot

```



```{r}
par(mfrow=c(1,3))

#residuals vs. fitted-values plo
plot(lm_new, which=1:2)


# residuals vs. order
plot(lm_new$residuals,
     main="Residuals Vs. Order")


#sum(coef(weather.lm)*c(1, 70))

```




